# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d0890cd72c726c37ae6ec791bf5f06ed6f083290b638781339355c1cf30ead8f89ce452b41074526b06c30d2aa01b247ffcf4a3314c362c3db5001ba0eeda4

test:
  secret_key_base: 25c655c853e07a26b600cc6942182d0dcbbdf875056cc1a0edf06a6d85591cd3bceeffa103ed4f731892ca57ecdc0a6f978597d907d1cfc005f90ca58b4f81ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
